### ISSUE TITLE
Possible bug surfacing in rvi_capture

### ISSUE THREAD

**Issue by andrewmusselman** [libimobiledevice/libimobiledevice#900]
https://github.com/gh2o/rvi_capture/issues/4

I'm encountering this bug where a packet capture utility says it has "Not Enough Data" which seems to occur in this library. Any ideas?

On Ubuntu with a device running iOS 13.3.

```Traceback (most recent call last):
  File "./rvi_capture.py", line 364, in <module>
    main()
  File "./rvi_capture.py", line 354, in main
    packet_dumper.run(packet_callback)
  File "./rvi_capture.py", line 295, in run
    for pkt in self.pkt_iter:
  File "./rvi_capture.py", line 183, in __iter__
    [chunk_len] = UB32.unpack(read_fully(4))
  File "./rvi_capture.py", line 178, in read_fully
    b += conn.recv(n - l)
  File "./rvi_capture.py", line 123, in recv
    self.handle, out, num_bytes, ctypes.byref(out_bytes), ctypes.c_uint(500)))
  File "./rvi_capture.py", line 59, in check
    raise cls(err)
__main__.IDeviceError: Error in libimobiledevice: Not Enough Data
```

**Comment by oi23mkoshiba** [comment]
I'm Japanese, so I apologize for my poor English.

I got this bug, too.
But my packet capture utility says it has "Missing Error".

On Fedora 31 with device running iOS 12.4.5
```
Traceback (most recent call last):
  File "./debugtest.py", line 371, in <module>
    main()
  File "./debugtest.py", line 361, in main
    packet_dumper.run(packet_callback)
  File "./debugtest.py", line 295, in run
    for pkt in self.pkt_iter:
  File "./debugtest.py", line 183, in __iter__
    [chunk_len] = UB32.unpack(read_fully(4))
  File "./debugtest.py", line 178, in read_fully
    b += conn.recv(n - l)
  File "./debugtest.py", line 123, in recv
    self.handle, out, num_bytes, ctypes.byref(out_bytes), ctypes.c_uint(500)))
  File "./debugtest.py", line 59, in check
    raise cls(err)
__main__.IDeviceError: Error in libimobiledevice: Missing Error

```

**Comment by N8TFly** [comment]
@oi23mkoshiba did you manage to get it working?

**Comment by oi23mkoshiba** [comment]
> @oi23mkoshiba did you manage to get it working? I have the same error

@N8TFly 
Sorry, I use translate.google.com.
I can now use rvi_capture.
The cause was "usbmuxd" running inside the program.
The new version of "usbmuxd" had a bug that didn't load the iPhone well.
So, when I downgraded "usbmuxd", rvi_capture worked fine.
In the Fedora, I ran the command: `sudo dnf downgrade usbmuxd`

**Comment by mexmer** [comment]
if rvi doesn't work with latest usbmux, it means rvi needs to be upgraded

**Comment by gh2o** [comment]
Issue was in rvi_capture and was solved, please close this bug.
